
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsDataAnalysis/FWNode/MINTS_001e06323a06_GPSGPGGA_2019_04_29.csv
%
% Auto-generated by MATLAB on 04-Jun-2019 17:44:06

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "timestamp", "latitude", "latitudeDirection", "longitude", "longitudeDirection", "gpsQuality", "numberOfSatellites", "HorizontalDilution", "altitude", "altitudeUnits", "undulation", "undulationUnits", "age", "stationID"];
opts.VariableTypes = ["string", "datetime", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "categorical", "double", "categorical", "string", "double"];
opts = setvaropts(opts, 2, "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, [1, 14], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 4, 6, 11, 13, 14], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsDataAnalysis/FWNode/MINTS_001e06323a06_GPSGPGGA_2019_04_29.csv", opts);

%% Convert to output type
dateTime = tbl.dateTime;
timestamp = tbl.timestamp;
latitude = tbl.latitude;
latitudeDirection = tbl.latitudeDirection;
longitude = tbl.longitude;
longitudeDirection = tbl.longitudeDirection;
gpsQuality = tbl.gpsQuality;
numberOfSatellites = tbl.numberOfSatellites;
HorizontalDilution = tbl.HorizontalDilution;
altitude = tbl.altitude;
altitudeUnits = tbl.altitudeUnits;
undulation = tbl.undulation;
undulationUnits = tbl.undulationUnits;
age = tbl.age;
stationID = tbl.stationID;

%% Clear temporary variables
clear opts tbl