
%% MAIN 0: Definitions

clc 
clear all
close all 

addpath("../../functions/")

% dataFolderPre      = "/home/lhw150030/mintsData"
dataFolderPre   = "/media/teamlary/Team_Lary_2/air930/mintsData"

dtSteps = [seconds(30)]  

deliverablesFolder = dataFolderPre + "/deliverables"


startDate  = datetime(2019,04,30);
% breakDate  = datetime(2019,07,17);
endDate    = datetime(2019,08,30);

nodeID            = "001e06305a12";
modelsFolderPre   =  deliverablesFolder + "/models"
pvalid            =20/100;
noptimizations    =30;



 %--------------------------------------------------------------------------
    nodeList={...
        nodeID ...
        };

    
    WantedVariables={...
%     'airTemperature',...
%     'relativeHumidity',...
    'barrometricPressureBars_YXXDRRetime',...
%     'dewPoint'...
    };
    

    WantedVariablesNames={...
%             'Temperature',...
%             'Humidity',...
             'Pressure',...        
%             'Dew Point'...
        };

    
     AllVariables={...
         'latitudeCoordinate_GPSGPRMCRetime',...
         'longitudeCoordinate_GPSGPRMCRetime',...
         'speedOverGround',...
         'latitudeCoordinate_GPSGPGGARetime',...
         'longitudeCoordinate_GPSGPGGARetime',...
         'gpsQuality_mints',...
         'numberOfSatellites_mints',...
         'HorizontalDilution',...
         'altitude_mints',...
         'undulation',...
         'valid_OPCN2',...
         'binCount0_OPCN2',...
         'binCount1_OPCN2',...
         'binCount2_OPCN2',...
         'binCount3_OPCN2',...
         'binCount4_OPCN2',...
         'binCount5_OPCN2',...
         'binCount6_OPCN2',...
         'binCount7_OPCN2',...
         'binCount8_OPCN2',...
         'binCount9_OPCN2',...
         'binCount10_OPCN2',...
         'binCount11_OPCN2',...
         'binCount12_OPCN2',...
         'binCount13_OPCN2',...
         'binCount14_OPCN2',...
         'binCount15_OPCN2',...
         'bin1TimeToCross_OPCN2',...
         'bin3TimeToCross_OPCN2',...
         'bin5TimeToCross_OPCN2',...
         'bin7TimeToCross_OPCN2',...
         'sampleFlowRate_OPCN2',...
         'temperatureOrPressure_OPCN2',...
         'samplingPeriod_OPCN2',...
         'checkSum_OPCN2',...
         'pm1_OPCN2',...
         'pm2_5_OPCN2',...
         'pm10_OPCN2',...
         'temperature_BME280',...
         'pressure_BME280',...
         'humidity_BME280',...
         'altitude_BME280',...
         'nh3_MGS001',...
         'co_MGS001',...
         'no2_MGS001',...
         'c3h8_MGS001',...
         'c4h10_MGS001',...
         'ch4_MGS001',...
         'h2_MGS001',...
         'c2h5oh_MGS001',...
         'UTCTimeStamp',...
         'latitude',...
         'longitude',...
         'gpsQuality_mintsAirMar',...
         'numberOfSatellites_mintsAirMar',...
         'horizontalDilution',...
         'altitude_mintsAirMar',...
         'geoidalSeparation',...
         'heading',...
         'barrometricPressureMercury',...
         'barrometricPressureBars_mints',...
         'airTemperature',...
         'relativeHumidity',...
         'dewPoint',...
         'windAngle',...
         'windSpeed',...
         'barrometricPressureBars_YXXDRRetime'...
         };


    RegressionVariables=  {...  
         'binCount0_OPCN2',...
         'binCount1_OPCN2',...
         'binCount2_OPCN2',...
         'binCount3_OPCN2',...
         'binCount4_OPCN2',...
         'binCount5_OPCN2',...
         'binCount6_OPCN2',...
         'binCount7_OPCN2',...
         'binCount8_OPCN2',...
         'binCount9_OPCN2',...
         'binCount10_OPCN2',...
         'binCount11_OPCN2',...
         'binCount12_OPCN2',...
         'binCount13_OPCN2',...
         'binCount14_OPCN2',...
         'binCount15_OPCN2',...
         'bin1TimeToCross_OPCN2',...
         'bin3TimeToCross_OPCN2',...
         'bin5TimeToCross_OPCN2',...
         'bin7TimeToCross_OPCN2',...
         'sampleFlowRate_OPCN2',...
         'pm1_OPCN2',...
         'pm2_5_OPCN2',...
         'pm10_OPCN2',...
         'temperature_BME280',...
         'pressure_BME280',...
         'humidity_BME280',...
         'altitude_BME280',...
         'nh3_MGS001',...
         'co_MGS001',...
         'no2_MGS001',...
         'c3h8_MGS001',...
         'c4h10_MGS001',...
         'ch4_MGS001',...
         'h2_MGS001',...
         'c2h5oh_MGS001',...
           };

    RegressionVariablesLabels={...
         'Bin 0',...
         'Bin 1',...
         'Bin 2',...
         'Bin 3',...
         'Bin 4',...
         'Bin 5',...
         'Bin 6',...
         'Bin 7',...
         'Bin 8',...
         'Bin 9',...
         'Bin 10',...
         'Bin 11',...
         'Bin 12',...
         'Bin 13',...
         'Bin 14',...
         'Bin 15',...
         'Bin 1 Time to Cross',...
         'bin 3 Time to Cross',...
         'bin 5 Time to Cross',...
         'bin 7 Time to Cross',...
         'Sample Flow Rate',...
         'PM_{1}',...
         'PM_{2.5}',...
         'PM_{10}',...
         'Temperature BME280',...
         'Pressure BME280',...
         'Humidity BME280',...
         'Altitude BME280',...
        'NH_3',...
        'CO',...
        'NO_2',...
        'C_3H_8',...
        'C_4H_10',...
        'CH_4',...
        'H_2',...
        'C_2H_5OH',...
        };

    %% mainCalib1 : Node Calibration 
mainAirMarCalib1_CalibratingNode    
    