function [] = printCSVDaily(calibrated,wantedOut,calibratedFolder,nodeID,givenDate,stringIn)
%PRINTCSVDAILY Summary of this function goes here
                    
    outCalibrated            = calibrated(:,wantedOut);
    outCalibratedFileName    = strcat(calibratedFolder,"/",nodeID,"/",...
                                                     num2str(year(givenDate),'%04d'),"/",...
                                                     num2str(month(givenDate),'%02d'),"/",...
                                                     num2str(day(givenDate),'%02d'),"/",...
                                                     "MINTS_",...
                                                     nodeID,...
                                                     "_",stringIn,"_",...
                                                     num2str(year(givenDate),'%02d'),"_",...
                                                     num2str(month(givenDate),'%02d'),"_",...
                                                     num2str(day(givenDate),'%02d'),".csv"...
                                                 );  

    mkdir(fileparts(outCalibratedFileName));
    writetimetable(outCalibrated,outCalibratedFileName)
end

