

load(strcat("mints_1_",strrep(string(dt)," ","_"),"_Chuncks.mat"))

inputs =   mints(:,{...
            'binCount0_OPCN3',...
            'binCount1_OPCN3',...
            'binCount2_OPCN3',...
            'binCount3_OPCN3',...
            'binCount4_OPCN3',...
            'binCount5_OPCN3',...
            'binCount6_OPCN3',...
            'binCount7_OPCN3',...
            'binCount8_OPCN3',...
            'binCount9_OPCN3',...
            'binCount10_OPCN3',...
            'binCount11_OPCN3',...
            'binCount12_OPCN3',...
            'binCount13_OPCN3',...
            'binCount14_OPCN3',...
            'binCount15_OPCN3',...
            'binCount16_OPCN3',...
            'binCount17_OPCN3',...
            'binCount18_OPCN3',...
            'binCount19_OPCN3',...
            'binCount20_OPCN3',...
            'binCount21_OPCN3',...
            'binCount22_OPCN3',...
            'binCount23_OPCN3',...
            'pm1_OPCN3',...
            'pm2_5_OPCN3',...
            'pm10_OPCN3',...
            'temperature_BME280',...
            'humidity_BME280',...
            'pressure_BME280',...
            'nh3_MGS001',...
            'co_MGS001',...
            'no2_MGS001',...    
            'c3h8_MGS001',...  
            'c4h10_MGS001',...
            'ch4_MGS001',...
            'h2_MGS001',... 
            'c2h5oh_MGS001',...   
            'c02_SCD30',...
            'temperature_SCD30',...
            'humidity_SCD30',...   
            });
            
 
    pm1   = mints(:,'pm1_grimm');
    pm2_5 = mints(:,'pm2_5_grimm');
    pm10  = mints(:,'pm10_grimm');
  
  
    pm1Mints =[inputs,pm1];
   
    pm2_5Mints =[inputs,pm2_5];

    pm10Mints =[inputs,pm10];


eval(strcat("save mints_2_",strrep(string(dt)," ","_"),"_Chuncks"))

 
 
 
 
