
clc 
clear all
close all 

addpath("../../functions/")

% dataFolderPre      = "/home/lhw150030/mintsData"
dataFolderPre   = "/media/teamlary/Team_Lary_2/air930/mintsData"

dtSteps = [seconds(30)];  

dt      = seconds(30);

deliverablesFolder = dataFolderPre + "/deliverables"

 
startDate  = datetime(2019,04,30);
breakDate  = datetime(2019,07,17);
endDate    = datetime(2019,08,16);

nodeID               = "001e06305a12";
% VersionSt            = "Version_RE_2019_08_28";
VersionStPalas       = "Version_RE_2019_08_28";                 
VersionStAirMar      = "Version_RE_AirMar2019_09_11";                 

modelsFolderPre   =  deliverablesFolder + "/models"

pvalid            =20/100;

noptimizations    =30;

modelsFolder = modelsFolderPre +"/"+strrep(string(dt)," ","")+"/"


 %--------------------------------------------------------------------------
    nodeList={...
        nodeID ...
        };

    WantedVariablesPalas={...
        'pm1_PALAS',...
        'pm2_5_PALAS',...
        'pm10_PALAS',...
        'pm4_PALAS',...
        'pmTotal_PALAS',...
        'dCn_PALAS'...
              };
          
    WantedVariablesNamesPalas={...
        'PM_{1}',...
        'PM_{2.5}',...
        'PM_{10}',...
        'PM_{4}',...
        'PM_{total}',...
        'dCn',...   
        };

    
        WantedVariablesAirMar={...
            'airTemperature',...
            'relativeHumidity',...
            'barrometricPressureBars_YXXDRRetime',...
            'dewPoint'...
        };
    

    WantedVariablesNamesAirMar={...
            'Temperature',...
            'Humidity',...
             'Pressure',...        
            'Dew Point'...    
        };
    
    
    
    AllVariables={...  
        'latitudeCoordinate_GPSGPRMC2',...
         'longitudeCoordinate_GPSGPRMC2',...
         'speedOverGround_GPSGPRMC2',...
         'latitudeCoordinate_GPSGPGGA2',...
         'longitudeCoordinate_GPSGPGGA2',...
         'gpsQuality_GPSGPGGA2',...
         'numberOfSatellites_GPSGPGGA2',...
         'HorizontalDilution_GPSGPGGA2',...
         'altitude_GPSGPGGA2',...
         'undulation_GPSGPGGA2',...
         'valid_OPCN2',...
         'Bin 0_OPCN2',...
         'binCount1_OPCN2',...
         'binCount2_OPCN2',...
         'binCount3_OPCN2',...
         'binCount4_OPCN2',...
         'binCount5_OPCN2',...
         'binCount6_OPCN2',...
         'binCount7_OPCN2',...
         'binCount8_OPCN2',...
         'binCount9_OPCN2',...
         'binCount10_OPCN2',...
         'binCount11_OPCN2',...
         'binCount12_OPCN2',...
         'binCount13_OPCN2',...
         'binCount14_OPCN2',...
         'binCount15_OPCN2',...
         'bin1TimeToCross_OPCN2',...
         'bin3TimeToCross_OPCN2',...
         'bin5TimeToCross_OPCN2',...
         'bin7TimeToCross_OPCN2',...
         'sampleFlowRate_OPCN2',...
         'temperatureOrPressure_OPCN2',...
         'samplingPeriod_OPCN2',...
         'checkSum_OPCN2',...
         'pm1_OPCN2',...
         'pm2_5_OPCN2',...
         'pm10_OPCN2',...
         'temperature_BME280',...
         'pressure_BME280',...
         'humidity_BME280',...
         'altitude_BME280',...
         'nh3_MGS001',...
         'co_MGS001',...
         'no2_MGS001',...
         'c3h8_MGS001',...
         'c4h10_MGS001',...
         'ch4_MGS001',...
         'h2_MGS001',...
         'c2h5oh_MGS001',...
         'luminosity_TSL2591',...
         'ir_TSL2591',...
         'full_TSL2591',...
         'visible_TSL2591',...
         'lux_TSL2591',...
         'rawUVA_VEML6075',...
         'rawUVB_VEML6075',...
         'visibleCompensation_VEML6075',...
         'irCompensation_VEML6075',...
         'uva_VEML6075',...
         'uvb_VEML6075',...
         'index_VEML6075',...
         'temperature_AS7262',...
         'violetPre_AS7262',...
         'bluePre_AS7262',...
         'greenPre_AS7262',...
         'yellowPre_AS7262',...
         'orangePre_AS7262',...
         'redPre_AS7262',...
         'violetCalibrated_AS7262',...
         'blueCalibrated_AS7262',...
         'greenCalibrated_AS7262',...
         'yellowCalibrated_AS7262',...
         'orangeCalibrated_AS7262',...
         'redCalibrated_AS7262'...
           };

    RegressionVariables=  {...  
         'binCount0_OPCN2',...
         'binCount1_OPCN2',...
         'binCount2_OPCN2',...
         'binCount3_OPCN2',...
         'binCount4_OPCN2',...
         'binCount5_OPCN2',...
         'binCount6_OPCN2',...
         'binCount7_OPCN2',...
         'binCount8_OPCN2',...
         'binCount9_OPCN2',...
         'binCount10_OPCN2',...
         'binCount11_OPCN2',...
         'binCount12_OPCN2',...
         'binCount13_OPCN2',...
         'binCount14_OPCN2',...
         'binCount15_OPCN2',...
         'bin1TimeToCross_OPCN2',...
         'bin3TimeToCross_OPCN2',...
         'bin5TimeToCross_OPCN2',...
         'bin7TimeToCross_OPCN2',...
         'sampleFlowRate_OPCN2',...
         'pm1_OPCN2',...
         'pm2_5_OPCN2',...
         'pm10_OPCN2',...
         'temperature_BME280',...
         'pressure_BME280',...
         'humidity_BME280',...
         'altitude_BME280',...
         'nh3_MGS001',...
         'co_MGS001',...
         'no2_MGS001',...
         'c3h8_MGS001',...
         'c4h10_MGS001',...
         'ch4_MGS001',...
         'h2_MGS001',...
         'c2h5oh_MGS001',...
           };

    RegressionVariablesLabels={...
      'Bin 0',...
         'Bin 1',...
         'Bin 2',...
         'Bin 3',...
         'Bin 4',...
         'Bin 5',...
         'Bin 6',...
         'Bin 7',...
         'Bin 8',...
         'Bin 9',...
         'Bin 10',...
         'Bin 11',...
         'Bin 12',...
         'Bin 13',...
         'Bin 14',...
         'Bin 15',...
         'Bin 1 Time to Cross',...
         'bin 3 Time to Cross',...
         'bin 5 Time to Cross',...
         'bin 7 Time to Cross',...
         'Sample Flow Rate',...
         'PM_{1}',...
         'PM_{2.5}',...
         'PM_{10}',...
         'Temperature BME280',...
         'Pressure BME280',...
         'Humidity BME280',...
         'Altitude BME280',...
        'NH_3',...
        'CO',...
        'NO_2',...
        'C_3H_8',...
        'C_4H_10',...
        'CH_4',...
        'H_2',...
        'C_2H_5OH',...
        };
    
    wantedOut=  {...   
         'latitudeCoordinate_GPSGPRMC2',...
         'longitudeCoordinate_GPSGPRMC2',...
         'altitude_GPSGPGGA2',...
         'binCount0_OPCN2',...
         'binCount1_OPCN2',...
         'binCount2_OPCN2',...
         'binCount3_OPCN2',...
         'binCount4_OPCN2',...
         'binCount5_OPCN2',...
         'binCount6_OPCN2',...
         'binCount7_OPCN2',...
         'binCount8_OPCN2',...
         'binCount9_OPCN2',...
         'binCount10_OPCN2',...
         'binCount11_OPCN2',...
         'binCount12_OPCN2',...
         'binCount13_OPCN2',...
         'binCount14_OPCN2',...
         'binCount15_OPCN2',...
         'pm1_PALAS',...
         'pm2_5_PALAS',...
         'pm4_PALAS',...
         'pm10_PALAS',...
         'pmTotal_PALAS',...
         'dCn_PALAS'...
         'airTemperature',...
         'relativeHumidity',...
         'barrometricPressureBars_YXXDRRetime',...
         'dewPoint'...
           };

          wantedOutLabels=  {...   
         'Latitude',...
         'Longitude',...
         'Altitude',...
         'Bin0',...
         'Bin1',...
         'Bin2',...
         'Bin3',...
         'Bin4',...
         'Bin5',...
         'Bin6',...
         'Bin7',...
         'Bin8',...
         'Bin9',...
         'Bin10',...
         'Bin11',...
         'Bin12',...
         'Bin13',...
         'Bin14',...
         'Bin15',...
         'PM1',...
         'PM2_5',...
         'PM4',...
         'PM10',...
         'PMTotal',...
         'dCn'...
         'Temperature',...
         'Humidity',...
         'Pressure',...        
         'DewPoint'...    
           };

      
  mainDaily1_saveAllTimeRangeData
    
    